### ISSUE TITLE
Updates for Installation instructions since R was updated to 3.6

### ISSUE THREAD

**Issue by hhollandmoritz** [fiererlab/dada2_fiererlab#14]
Now that R is updated, we need to update the installation instructions for the ShortRead package. 

Details here:
https://bioconductor.org/packages/release/bioc/html/ShortRead.html

**Comment by hhollandmoritz** [comment]
Note, the instructions on the linked page say that it only works for R 4.0, the code also works fro R 3.6 (current version on the server as of this posting date).

**Comment by cliffbueno** [comment]
In addition to the ShortRead fix (which worked!), use BiocManager::install(“dada2”, version = “3.10") instead of version 3.8. Otherwise you will get the error "Error: Bioconductor version '3.8' requires R version '3.5'; see https://bioconductor.org/install"

**Comment by cliffbueno** [comment]
Next update will include updated install instructions for R 4.4.1, as per #30
