### ISSUE TITLE
Need to add alternative option for "5. Summary of reads throughout pipeline" if samples=pooled

### ISSUE THREAD

**Issue by ndragone** [fiererlab/dada2_fiererlab#15]
If samples=pooled need to use:
`ddF_track <- data.frame(denoisedF = sapply(derepF.p[sample.names], getN)) %>%
  mutate(Sample = row.names(.))
ddR_track <- data.frame(denoisedR = sapply(derepR.p[sample.names], getN)) %>%
  mutate(Sample = row.names(.))`

instead of:
`ddF_track <- data.frame(denoisedF = sapply(ddF[sample.names], getN)) %>%
  mutate(Sample = row.names(.))
ddR_track <- data.frame(denoisedR = sapply(ddR[sample.names], getN)) %>%
  mutate(Sample = row.names(.))`

**Comment by cliffbueno** [comment]
This has been implemented in my new working version and will be released in version 2.0.0.
