### ISSUE TITLE
Add clarity about Reverse Complementing barcodes

### ISSUE THREAD

**Issue by hhollandmoritz** [fiererlab/dada2_fiererlab#16]
On line 165:
https://github.com/fiererlab/dada2_fiererlab/blob/81f578d3bc4561e532a1060af8a0b670080cba8a/dada2_tutorial_16S.R#L165

Replace "For ITS Sequences" with "For ITS, 18S, and Univeral Barcode Primers:" since these three primer sets from our lab result in reverse-complemented barcodes.

Also update the text to say something like this: 

> Depending on how your sequences were run and how your primers were designed your barcodes may need to be reverse-complemented. A good clue that you might need to reverse complement your barcodes is if your first attempt at demultiplexing results in the wrong number of demultiplexed files, or if your demultiplexed files are really small. Here is a link to a handy tool, that can help you reverse complement your barcodes: http://arep.med.harvard.edu/labgc/adnan/projects/Utilities/revcomp.html

**Comment by cliffbueno** [comment]
This has been implemented in my new working version and will be released in version 2.0.0.
