### ISSUE TITLE
save intermediate steps?

### ISSUE THREAD

**Issue by corinnewalsh** [fiererlab/dada2_fiererlab#20]
Is it worth it to save intermediate steps (eg error, merged reads), incase R studio kicks you out? We could delete saved intermediate steps at the very end of the pipeline.

**Comment by realmichaelhoffert** [comment]
I definitely think this is worth doing, also handy if you run out of time to run things and don't want to leave the session running, or need to unexpectedly clear the environment. Pretty easy to add saving a workspace image

**Comment by cliffbueno** [comment]
Merged reads is just 1 step away from the sequence table which is saved, so don't think we need to save merged reads. In version 2.0.0 I am saving the errF and errR objects in addition to the plots as learning errors does take a while.
