### ISSUE TITLE
Instructions and process for regenerating .html, .R, .Rmd, files

### ISSUE THREAD

**Issue by realmichaelhoffert** [fiererlab/dada2_fiererlab#22]
When I make updates to the pipeline, I'm not sure if I should update the pipeline R file, submit a pull request which is merged, and then reknit the docs and push to master, or do everything and merge knitted docs to master. It doesn't really matter, I'd just like a bit more clarity on how to finalize changes I've made to the pipeline

**Comment by cliffbueno** [comment]
I don't think it matters, just do whatever is easiest.

**Comment by realmichaelhoffert** [comment]
I'm so glad I got an email to inform me of this helpful comment

**Comment by cliffbueno** [comment]
For version 2.0.0 I am updating the .Rmd and then will reknit and merge.

**Comment by cliffbueno** [comment]
FYI I separately knitted a .html, saved a copy as .R, and then for the .md set the knit output to "github_document"
