### ISSUE TITLE
Add in details about variable read lengths, merging, etc., especially in regards to ITS

### ISSUE THREAD

**Issue by clairecwinfrey** [fiererlab/dada2_fiererlab#25]
Clarify in tutorial about how ITS (and maybe datasets generated with other primer sets??) have variable read lengths, some of which mean that reads do not overlap and cannot be merged. Could be good to add in link to Ben Callahan's ITS explanation and workflow for dada2: https://benjjneb.github.io/dada2/ITS_workflow.html

**Comment by cliffbueno** [comment]
This has been implemented in my new working version and will be released in version 2.0.0.
