### ISSUE TITLE
Add instructions to end of tutorial about how to format for phyloseq?

### ISSUE THREAD

**Issue by clairecwinfrey** [fiererlab/dada2_fiererlab#26]
Phyloseq allows you to create and easily manipulate an object that contains an ASV table, metadata, taxonomy table, and (optionally) a tree. I've found that it makes microbiome analysis more straightforward, especially when I didn't know how to use tidy verse tools. Would it be helpful for me to add optional code at the end of tutorial for getting data formatted for phyloseq?

**Comment by cliffbueno** [comment]
yes, that could go below the mctoolsr formatting part.

**Comment by cliffbueno** [comment]
Added a small bit of example code to make a phyloseq object in Version 2.0.0.
