### ISSUE TITLE
Better explanation for barcode file order 

### ISSUE THREAD

**Issue by gebertm** [fiererlab/dada2_fiererlab#28]
<Barcode> <sampleID>

**Comment by cliffbueno** [comment]
@gebertm can you clarify what you mean by this? Do you mean to explain that the barcode file should have a column of barcodes and a column of sample IDs?

**Comment by gebertm** [comment]
Correct - it's in there somewhere (that it should go <barcode> <sampleID>) but emphasizing that the order is important. I think at the moment it is buried in a comment somewhere in the tutorial, when you load the barcode file in.

**Comment by cliffbueno** [comment]
Ok got it. Will be released in version 2.0.0
