### ISSUE TITLE
plotQualityProfile function has deprecated argument

### ISSUE THREAD

**Issue by sjech** [fiererlab/dada2_fiererlab#29]
The plotQualityProfile function on Lines 187-194 produces a warning related to ggplot version. 
Warning message shown below in screenshot.

![Screen Shot 2023-06-13 at 11 13 04 AM](https://github.com/fiererlab/dada2_fiererlab/assets/44000112/0722e20a-54c7-4b56-9040-f9c76f7a816e)

**Comment by cliffbueno** [comment]
That's internal to dada2 though, not a custom function of our pipeline.

**Comment by cliffbueno** [comment]
This error no longer appears in R 4.4.1 and DADA2 1.32.0
