### ISSUE TITLE
Emphasize the Silva database should not be used for 18S

### ISSUE THREAD

**Issue by hhollandmoritz** [fiererlab/dada2_fiererlab#3]
There are two different silva database versions formatted for dada2. One is geared towards 16S analysis (the one currently referenced) and another is geared towards 18S. We should make it clearer in the pipeline that the silva database that is referenced should NOT be used for 18S purposes.

**Comment by cliffbueno** [comment]
This has been implemented in my new working version and will be released in version 2.0.0.
